name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set environment variable
      run: echo "CI=true" >> $GITHUB_ENV
      
    - name: Install dependencies
      run: npm ci --strict-peer-dependencies
